# Generated by Django 5.1.2 on 2024-12-19 16:28

import bodegaApp.models.helpers.categoriaDefaults
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjunto', models.FileField(upload_to='adjuntos/')),
                ('nombre', models.CharField(max_length=500)),
                ('fecha', models.DateField(auto_now=True)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=75)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTag', models.CharField(max_length=6)),
                ('activo', models.BooleanField()),
                ('adjunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegaApp.adjunto')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTag', models.CharField(max_length=6)),
                ('comentario', models.TextField()),
                ('adjunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegaApp.adjunto')),
            ],
            options={
                'verbose_name': 'Locker',
                'verbose_name_plural': 'Lockers',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('adjunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegaApp.adjunto')),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bodegaApp.caja')),
                ('categoria', models.ForeignKey(default=bodegaApp.models.helpers.categoriaDefaults.get_default_categoria, on_delete=models.SET(bodegaApp.models.helpers.categoriaDefaults.get_default_categoria), to='bodegaApp.categoria')),
                ('locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bodegaApp.locker')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.AddField(
            model_name='caja',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegaApp.locker'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('foto_perfil', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bodegaApp.adjunto')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bodegaApp.persona')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('notas', models.TextField()),
                ('estado', models.IntegerField(choices=[(1, 'En préstamo'), (2, 'Devuelto'), (3, 'Perdido'), (4, 'Anulado'), (5, 'Otros')], default=1)),
                ('adjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bodegaApp.adjunto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegaApp.insumo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegaApp.persona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
