# Generated by Django 5.1.4 on 2024-12-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaApp', '0002_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='user_id',
            new_name='user',
        ),
    ]
